### ISSUE TITLE
NPM dependencies plugin(s)

### ISSUE THREAD

**Issue by matejchalk** [code-pushup/cli#542]
### User story

As a Code PushUp user, I would like to see **security vulnerabilities** from my NPM packages listed and used to calculate a _Security_ category score. I would also like to know about **out-of-date packages**, which can be used in an _Up-to-date_ or _Future proof_ category.

It would be great to have support for all the commonly used package managers:

- [x] NPM
- [x] Yarn classic (v1) 
- [x] Yarn modern (v2+)
- [x] PNPM

### Acceptance criteria
- [x] 1 plugin for all (`@code-pushup/js-packages-plugin`)
- [x] let user configure which of the package manager should be running
- [x] How do we integrate audit levels (`info`, `low`, `moderate`, `high`, `critical`) with issue severities?
  - extend issue severity enum in our data models (current: `info`, `warning`, `error`)?
  - [x] convert them to existing levels (e.g. `info` ➡ `info`, `low`/`moderate` ➡ `warning`, `high`/`critical` ➡ `error`)?
    - [x] keep this option as default but let it configurable

### Implementation details

The commands to list vulnerabilities and outdated packages are similar for NPM, Yarn 1 and PNPM, since they're all based on the NPM CLI. However, Yarn 2+ has a an altogether different set of commands, so alternatives must be found there (more details in [migration guide](https://yarnpkg.com/migration/guide)).

| Package manager | Vulnerabilities command | Outdated command |
| :-- | :-- | :-- |
| [NPM](https://www.npmjs.com/) | [`npm audit --json`](https://docs.npmjs.com/cli/v10/commands/npm-audit) | [`npm outdated --json`](https://docs.npmjs.com/cli/v10/commands/npm-outdated) |
| [Yarn 1](https://classic.yarnpkg.com/en/) | [`yarn audit --json`](https://classic.yarnpkg.com/en/docs/cli/audit) | [`yarn outdated --json`](https://classic.yarnpkg.com/lang/en/docs/cli/outdated/) |
| [Yarn 2+](https://yarnpkg.com/) | [`yarn npm audit --json`](https://yarnpkg.com/cli/npm/audit) | no built-in command (see https://github.com/yarnpkg/berry/issues/749), but there is a [Yarn plugin](https://github.com/mskelton/yarn-plugin-outdated)  |
| [PNPM](https://pnpm.io/) | [`pnpm audit --json`](https://pnpm.io/cli/audit) | [`pnpm outdated --json`](https://pnpm.io/cli/outdated) |

**Comment by BioPhoton** [comment]
> How do we integrate audit levels (info, low, moderate, high, critical) with issue severities?

One alternative could be to put the audit result into a new data field, display them as table and calculate one result for the audit from all detected packages.

**Comment by Tlacenka** [comment]
The first version of the plugin is complete, therefore I am closing this issues. Any subsequent changes and fixes should be documented separately.
